name: Grace Doc
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  # Build job
  build:
    permissions:
      contents: read  #  to fetch code (actions/checkout)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    steps:
      - name: Checkout repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Get the current version
        id: current_version
        run: |
          echo "$(cat gradle.properties | grep 'projectVersion=' | awk '{print $1}')" >> "$GITHUB_OUTPUT"
      - name: Generate Docs
        id: build
        run: ./gradlew docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: rainboyan/deploy-github-pages@v1.1.0
        env:
          VERSION: ${{ steps.current_version.outputs.projectVersion }}
          TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
